version: '3'

services:

    vault:
      image: hashicorp/vault:1.19
      container_name: vault
      volumes:
        - ./vault/config:/vault/config
        - ./vault/policies:/vault/policies
        - ./vault/data:/vault/data
      ports:
        - 8200:8200
      environment:
        - VAULT_ADDR=https://0.0.0.0:8200
        - VAULT_API_ADDR=https://0.0.0.0:8200
        - VAULT_ADDRESS=https://0.0.0.0:8200
      cap_add:
        - IPC_LOCK
      command: vault server -config=/vault/config/vault.json